### PR TITLE
Update libraries with AR6GWP20

### PR DESCRIPTION
**Pull request by rgieseke**
- [ ] confirm/check (accidental?) rename of HFE449s1/HFE449sl (#11)
- [x] add to Readme

### CODE REVIEW

**Comment by danielhuppmann** [comment]
Just to not forget (I can't edit the description above, maybe include there and delete the comment)

- [ ] add to Readme

**Comment by danielhuppmann** [comment]
Preparing for a new release of iam-units, any chance to merge this soon?

**Comment by rgieseke** [comment]
> Preparing for a new release of iam-units, any chance to merge this soon?

Do you pin to a specific version in iam-units? I think this package will probably need some decisions re < and weirdly named HFCs and then hopefully won't see many updates for the next, uhm, 6 or 7 years ...

**Comment by rgieseke** [comment]
(Ah, right, you use it for generated code ...and just saw it's already merged on your side)

**Comment by danielhuppmann** [comment]
Yes, using globalwarmingpotentials to generate "hard-coded" GWP factors seems like a decent trade-off - better than copy-pasting csv files without the hassle of having to keep different packages in sync so that they play nice...

**Comment by znicholls** [comment]
Can we just put nans for things where we haven't made a decision yet, create an issue for this decision and merge this? It seems silly to hold up getting all the good stuff in this PR back for a decision which will make no difference to 99.999% of users.

**Comment by znicholls** [comment]
I see we already have the issue (#8) so this can be merged no?

**Comment by danielhuppmann** [comment]
+1 for merging quickly and revisit minor questions later

**Pull request merged**
