### PR TITLE
Add GWP100 data from AR6WG1 after approval with data source

### PR DESCRIPTION
**Pull request by jkikstra**
Adding data from the table in Chapter 7: The Earth's energy budget, climate feedbacks, and climate sensitivity - Supplementary Material from https://www.ipcc.ch/report/ar6/wg1/.

- [x] add data source
- [x] add data in csv
- [ ] add data in `__init__.py`

### CODE REVIEW

**Comment by jkikstra** [comment]
Thanks @znicholls for pointing out this useful great open source package. 
@rgieseke - if you like this addition, here's the data that got uploaded this morning.

The only thing i see that is left to do would be to add it to the dictionary in `__init__.py`.

**Comment by rgieseke** [comment]
Wicked, thank you!

Have you considered adding not yet covered ones like CFC-114a as well? 
Actually, i'm not sure whether we should have a machine-readable version of the entire table or focus on those relevant for the SCM/IAM communities.

Also GWP20 could be super nice as well (if you already have that).

**Comment by znicholls** [comment]
> Actually, i'm not sure whether we should have a machine-readable version of the entire table or focus on those relevant for the SCM/IAM communities.

My two cents, the latter. Copying the entire table by hand is a job for a day when we're really bored.

**Comment by znicholls** [comment]
> Copying the entire table by hand is a job for a day when we're really bored.

Or a job for the TSU/when the data underlying everything becomes available.

**Comment by rgieseke** [comment]
Ok - I had thought this was already available in some kind of machine readable (excel?) format ...

**Comment by znicholls** [comment]
Must be somewhere but the TSU haven't put up anything except SPM data yet

**Comment by jkikstra** [comment]
I agree with @znicholls , though if there is an excel file (zeb or chris, if we ask?) or if some automatic reading ([example link](https://www.adobe.com/documentcloud/acrobat/hub/how-to/how-to-convert-pdf-to-csv.html)) would work, it would be possible? 

The table has loads of different global warming potential versions in the table.

**Comment by znicholls** [comment]
Nice. I'd say let's merge this now and deal with adding more another day. @chrisroadmap would be the person to ask about getting an excel version.

**Comment by jkikstra** [comment]
I'm just chatting with him now so will ask directly.
Feel free to merge (i don't have the permissions i think).

**Comment by rgieseke** [comment]
Released as v0.7.0 (https://github.com/openclimatedata/globalwarmingpotentials/releases/tag/v0.7.0)

Thanks again @jkikstra !

**Comment by chrisroadmap** [comment]
Do you make use of CGTP50 and CGTP100? They have been updated by Bill Collins and the version in the untypeset version in table 7.SM.7 (https://www.ipcc.ch/report/ar6/wg1/downloads/report/IPCC_AR6_WGI_Chapter_07_Supplementary_Material.pdf) will be updated. If you don't use them, and 3 significant figures is OK for everything else, I have a cleaned CSV I'll send to Jarmo.

**Comment by rgieseke** [comment]
In pyam and openscm-related i think only GWP100 are relevant (please correct me if i'm wrong @znicholls, @danielhuppmann)

In general i think it would be great to have these tables in machine-readable form.

GWP20 (#10) would be useful to show the difference that it makes e.g. for methane.

**Comment by chrisroadmap** [comment]
GWP20 is also in there :)

I took in Bill Collins' raw data and wrote a script to clean it up and wrote it out to CSV, so it should be machine-readable. I'm still waiting to see whether I can release the chapter 7 repository as it's all in there.

**Comment by znicholls** [comment]
> Do you make use of CGTP50 and CGTP100?

They're only useable if you convert things using changes in emissions. At the moment neither openscm-units nor pyam has such functionality (and they wouldn't work in this static setup anyway) so I think for this repo at least we're in the clear.

**Pull request merged**
