### PR TITLE
add gwp20 from AR6 table provided by @chrisroadmap

### PR DESCRIPTION
**Pull request by jkikstra**
Addresses #10 

With thanks to @chrisroadmap for providing the data in a machine readable format which made the combining lots easier!

@rgieseke i leave updating the libraries to you again, if okay :)

### CODE REVIEW

**Comment by rgieseke** [comment]
Awesome, thanks both!

**Comment by rgieseke** [comment]
@jkikstra it should be HFE449s1 or HFE449sl?
I think the former, no?

**Comment by jkikstra** [comment]
@rgieseke Ah yes. forgot to mention. But luckily you have an eagle eye!

I saw that the csv file had HFE449sl, but AR6 has HFE449s1.
Then I went ahead and assumed AR6 was correct, but I wanted to ask because I don't actually know and the internet does not seem to give me the answer

**Comment by rgieseke** [comment]
Just had a diff https://github.com/openclimatedata/globalwarmingpotentials/pull/12/commits/e8209e690f9adbc68cd51496838a488aa3204760 :smile: 

So AR6 has

image

Our GHGprotocol source has

image

And this German Environmental Agency report has both (and both as HFE-7100)
image
image

https://www.umweltbundesamt.de/sites/default/files/medien/378/publikationen/climate_change_17_2015_implementierung_der_ab_dem_berichtsjahr_2013.pdf

I'd go with the AR6 variant, only concern would be names in openscm or pyam (cc/ @znicholls @danielhuppmann)

**Comment by danielhuppmann** [comment]
Don't see why either of these variants should be a problem for **iam_units** (and hence **pyam**), so no preference or objections here...

**Comment by chrisroadmap** [comment]
> Then I went ahead and assumed AR6 was correct

I wouldn't assume this :laughing:

**Comment by znicholls** [comment]
> I'd go with the AR6 variant, only concern would be names in openscm or pyam (cc/ @znicholls @danielhuppmann)

I don't think anyone has ever used this conversion so call it what you want :)

**Comment by rgieseke** [comment]
I think in the end it comes down to, do we want 

- a machine readable version of the tables in the IPCC reports and make as few changes to them as possible, or
- something refined and aggregated, which eases comparison between reports (and then document all changes)

We could have a row with `HFE449s1` and a row with `HFE449sl`. :man_shrugging:

**Pull request merged**
